config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get     '/help',    to: 'static_pages#help'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup',  to: 'dictum_users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  resources :gogakus , except: :index
  get     "/quick",   to:"static_pages#quick"
  get     "demo",     to:"static_pages#demo"
  resources :dictum_users , except: [:index, :show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :logged_in_user, only: [:quick]

    def home
      if logged_in?
        @gogaku = current_user.gogakus.build
        @feed_items = current_user.feed.paginate(page: params[:page])
      end
    end
  
    def help
      
    end
  
    def about
     
    end
  
    # def contact
      
    # end

    def quick
      render :layout => 'g_show'
    end

    def demo
      render :layout => 'g_show'
    end
  end
  

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<script>
function rel() {

    if (window.name != "any") {
        // alert("リロードしました");
        location.reload();
        window.name = "any";
    } else {
        window.name = "";
    }

    }
rel();
</script>
<% provide(:title, "About") %>
<h1><u>About</u></h1>

<p>
  音声の波形は<a href="https://www.wizard-notes.com/entry/javascript/wavesurfer-js">こちらのサイト</a>
  に載っているものを使用させていただきました。<a href="https://licenses.opensource.jp/BSD-3-Clause/BSD-3-Clause.html">
  使用させて頂いたコードのライセンスはこちら</a>
</p>

<p>サンプルBGMは<a href="https://dova-s.jp/bgm/download15445.html">こちらのサイト</a>からダウンロードさせていただきました。</p>
<p>イラストは<a href="https://storyset.com/online">Online illustrations by Storyset</a>を使用させていただきました。</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  
</p>

app/views/static_pages/demo.html.erb
<h2>sample</h2>
<h1><u>操作方法</u></h1>
<div>
    <h4>基本は画面クリックで操作をします。なお、「区域ループ再生」は区域の右側をクリックすることでループから脱出できます。</h4>
    <h4>・ctrl(コントロールキー) = スタート/ストップ ()<br>・←(左カーソルキー) = 3秒戻る <br>・→(右カーソルキー) = 3秒進む  </h4>
</div>
  <script src="https://unpkg.com/wavesurfer.js@6.0.4/dist/wavesurfer.js" type="text/javascript"></script>
  <script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js" type="text/javascript"></script>
      <div id="waveform"> </div>

      <div style="text-align: center">
          
          <p class="row">
              <div class="col-xs-1">
                  <i class="glyphicon glyphicon-zoom-in"></i>
              </div>

              <div class="col-xs-10">
                  <input id="slider" type="range" min="1" max="200" value="1" style="width: 100%" />
              </div>

              <div class="col-xs-1">
                  <i class="glyphicon glyphicon-zoom-out"></i>
              </div>
          </p>
      </div>

  <div class="container" style="text-align: center">
      <div class="controls" >
          <span>
              <button class="btn btn-primary col-sm-2" onclick="wavesurfer.skipBackward(5)"><i class="fa fa-step-backward"></i>5秒戻る</button>
              <button class="btn btn-primary col-sm-2" onclick="wavesurfer.playPause()"><i class="fa fa-play"></i>スタート/<i class="fa fa-pause"></i>ストップ</button>
              <button class="btn btn-primary col-sm-2" onclick="wavesurfer.skipForward(5)"><i class="fa fa-step-forward"></i>5秒進む</button>
              <select id="controller" class="btn btn-primary col-sm-2">
                  <option type="button" value="0.5">0.5</option>
                  <option type="button" value="0.75">0.75</option>
                  <option type="button" value="1.0" selected>1.0</option>
                  <option type="button" value="1.25">1.25</option>
                  <option type="button" value="1.5">1.5</option>     
                  <option type="button" value="1.75">1.75</option>
                  <option type="button" value="2.0">2.0</option>
              </select>
              <button class="btn btn-primary col-sm-2" id="loop">区域ループ再生</button>
            
          </span>
      </div>
  </div>

  <script>
      var wavesurfer = WaveSurfer.create({
              barRadius: 3,
              cursorWidth: 1,
              height: 230,barMinHeight: 1,
              barGap: 1,
              container: '#waveform',
              waveColor: 'gray',
              progressColor: 'orange',
              scrollParent: true,
              backend: 'MediaElementWebAudio',
              plugins: [
                  WaveSurfer.regions.create({
                
                      regions: [
                          {
                              start: 5,
                              end: 7,
                              loop: false,
                              color: 'hsla(200, 50%, 70%, 0.4)',
                          }
                      ],
            
                  })
              ]
      });



      var slider = document.querySelector('#slider');

      slider.oninput = function () {
          var zoomLevel = Number(slider.value);
          wavesurfer.zoom(zoomLevel);
      };
    

      const corsAudio = new Audio('/assets/Night_Sea.mp3');
      corsAudio.crossOrigin = true;
      
      wavesurfer.load(corsAudio);


  wavesurfer.on('ready', () => {
          console.log('ready');
          });


          function playPause() {
          wavesurfer.playPause();
      }
      
  let speed = document.getElementById('controller');

      speed.addEventListener('change', function() {
          let idx = speed.selectedIndex;
          let specon = speed.options[idx].text; 
          console.log(specon);  
          function playbackRate() {
              switch (specon) {
                  case 0.5:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
                  case 0.75:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
                  case 1.25:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
                  case 1.5:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
                  case 1.75:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
                  case 2.0:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
                  default:
                      rate = specon 
                      wavesurfer.setPlaybackRate(rate);
                      console.log(specon);  
                      break;
              }
      }
      playbackRate();
      })
            
  document.addEventListener('keydown', keydown_ivent);

      function keydown_ivent(e) {
    
    let key = '';
    switch (e.key) {
          case 'Control':
        wavesurfer.playPause();
        break;
      case 'ArrowLeft':
        wavesurfer.skipBackward(3);
        break;
      case 'ArrowRight':
              wavesurfer.skipForward(3);
        break;
    }
    return false;
  }

      let l = document.getElementById('loop');
      l.addEventListener('click', function() {
          let region = Object.values(wavesurfer.regions.list)[0];
          region.playLoop();
      });

  </script>

  <textarea rows="10" cols="50" placeholder="ここに文字を入力出来ます" class="box"></textarea>

app/views/static_pages/help.html.erb
<script>
function rel() {

    if (window.name != "any") {
        // alert("リロードしました");
        location.reload();
        window.name = "any";
    } else {
        window.name = "";
    }

    }
rel();
</script>

<% provide(:title, "Help") %>
<h1><u>Help</u></h1>

<h2 id="blue">操作方法</h2>
<h3>基本は画面クリックで操作をします。なお、「区域ループ再生」は区域の右側をクリックすることでループから脱出できます。</h3>
<h3>・ctrl(コントロールキー) = スタート/ストップ ()<br>・←(左カーソルキー) = 3秒戻る <br>・→(右カーソルキー) = 3秒進む  </h3>

<h4><span class="red">(注意)</span>
万が一エラーが発生した場合は、お手数ですがページのリロード（画面左上の再読み込みをクリック）をお願い致します。<br>
<span class="red">また、稀にですが、保存したファイルが破損してエラーになってしまう場合がございます</span>。その際はお手数ですが、ブラウザの戻るボタンを押してマイページに
戻っていただき、音声ファイルを削除のうえ、再度音声ファイルの登録をお願いいたします。<br>
なお、どうしてもエラーが頻繫に発生してしまう場合は、マイページの「クイックモード」をご使用ください。</h4>
<div class="explain">
    <h2 id="blue">通常モード</h2>
    <h4>・「新しく音声を登録」をクリックすることで音声を登録出来ます。登録時に教科、内容、音声、答えを登録します。なお、答えは必須ではありません</h4>
    <h4>・最大５つまで音声を登録出来ます.音声ファイルは<u>5MB以下</u>のものにしてください。</h4>
    <h4>・音声を登録後、「Let`s start studying」をクリックすることで学習ページに飛ぶことが出来ます。</h4>
    <h4>・<u>画面遷移後に画面全体が真っ白になったり、表示がバグる可能性がございます。その際はお手数ですが、ページのリロードをお願い致します。</u></h4>
    <h4>・「edit」で内容を変更、「delete」で保存内容の削除ができます。</h4>
</div>

<div class="explain">
    <h2 id="blue">クイックモード</h2>
    <h4>・音声ファイルのサイズの制限は付けていません。</h4>
    <h4>・「クイックモード」をクリックすることでクイックモードをご使用いただけます。</h4>
    <h4>・このモードでは音声ファイルを登録するだけで、すぐにご使用いただけます。</h4>
    <h4>・なお、<u>音声ファイルは保存されない</u>ため、ページのリロードなどの際には再度ファイルを選択してください。</h4>
    <h4 >・<u>画面遷移後に表示がバグる可能性がございます。その際はお手数ですが、ページのリロードをお願い致します。</u></h4>
    <h4 class="red">・音声ファイルのサイズ制限は特に設けておりませんが、再生するのに<a href="http://www.xucker.jpn.org/pc/wavesurfer_tips.html">最大元データーの20倍ほどのメモリが必要</a><br>
    との情報がございました。そのため、最大でも200Mバイトまでのデータにすることを強くお勧め致します。</h4>
    <h4 class="red">・なお、万が一お使いのコンピュータにアップロードした音声ファイルのサイズが原因で不具合、故障が発生したとしても、私は一切の責任を負いません。気を付けてご使用ください。</h4>
</div>

app/views/static_pages/home.html.erb
<canvas id="canvas"></canvas>
<script>
  var Canvas = document.getElementById('canvas');
var ctx = Canvas.getContext('2d');

var resize = function() {
    Canvas.width = Canvas.clientWidth;
    Canvas.height = Canvas.clientHeight;
};
window.addEventListener('resize', resize);
resize();

var elements = [];
var presets = {};

presets.o = function (x, y, s, dx, dy) {
    return {
        x: x,
        y: y,
        r: 12 * s,
        w: 5 * s,
        dx: dx,
        dy: dy,
        draw: function(ctx, t) {
            this.x += this.dx;
            this.y += this.dy;
            
            ctx.beginPath();
            ctx.arc(this.x + + Math.sin((50 + x + (t / 10)) / 100) * 3, this.y + + Math.sin((45 + x + (t / 10)) / 100) * 4, this.r, 0, 2 * Math.PI, false);
            ctx.lineWidth = this.w;
            ctx.strokeStyle = '#fff';
            ctx.stroke();
        }
    }
};

presets.x = function (x, y, s, dx, dy, dr, r) {
    r = r || 0;
    return {
        x: x,
        y: y,
        s: 20 * s,
        w: 5 * s,
        r: r,
        dx: dx,
        dy: dy,
        dr: dr,
        draw: function(ctx, t) {
            this.x += this.dx;
            this.y += this.dy;
            this.r += this.dr;
            
            var _this = this;
            var line = function(x, y, tx, ty, c, o) {
                o = o || 0;
                ctx.beginPath();
                ctx.moveTo(-o + ((_this.s / 2) * x), o + ((_this.s / 2) * y));
                ctx.lineTo(-o + ((_this.s / 2) * tx), o + ((_this.s / 2) * ty));
                ctx.lineWidth = _this.w;
                ctx.strokeStyle = c;
                ctx.stroke();
            };
            
            ctx.save();
            
            ctx.translate(this.x + Math.sin((x + (t / 10)) / 100) * 5, this.y + Math.sin((10 + x + (t / 10)) / 100) * 2);
            ctx.rotate(this.r * Math.PI / 180);
            
            line(-1, -1, 1, 1, '#fff');
            line(1, -1, -1, 1, '#fff');
            
            ctx.restore();
        }
    }
};

for(var x = 0; x < Canvas.width; x++) {
    for(var y = 0; y < Canvas.height; y++) {
        if(Math.round(Math.random() * 8000) == 1) {
            var s = ((Math.random() * 5) + 1) / 10;
            if(Math.round(Math.random()) == 1)
                elements.push(presets.o(x, y, s, 0, 0));
            else
                elements.push(presets.x(x, y, s, 0, 0, ((Math.random() * 3) - 1) / 10, (Math.random() * 360)));
        }
    }
}

setInterval(function() {
    ctx.clearRect(0, 0, Canvas.width, Canvas.height);

    var time = new Date().getTime();
    for (var e in elements)
    elements[e].draw(ctx, time);
}, 10);
</script>

<% if logged_in? %>
<script>
  window.onpageshow = function(event) {
    if (event.persisted) {
      window.location.reload();
    }
  };
</script>
  <% if flash.any? %>
    <% flash.each do |message_type, message| %>
    
      <div class="alert alert-danger" role="alert"><%= message %></div>
    
  <% end %>
<% end %>


  <div class="row">
    <aside class="col-md-6">
      <section class="dictum_user_info">
        <%= render 'shared/dictum_user_info' %>
      </section>
      <% if current_user.gogakus.count < 5%>
        <section class="gogaku_form">
          <%= link_to "新しい音声を登録(最大5つまで)", new_gogaku_path, class: "btn btn-success btn-lg glyphicon glyphicon-plus-sign"%>
        </section>
      <% else %>
          <%= link_to "新しい音声をこれ以上登録出来ません", "#" , class: "btn btn-success btn-lg glyphicon glyphicon-exclamation-sign"%>
      <% end %>
    </aside>
    <aside class="col-md-6">
      <section class="quick_backcolor" id="quick">
            <%= link_to "クイックモード", quick_path, class: "btn btn-primary btn-lg glyphicon glyphicon-time",data: { 'turbolinks': false }%>
      
            <h3>保存する必要がなかったり、エラーが頻発する際にお使いください。<br>音声ファイルを選択するだけでご使用いただけます。</h3>
      </section>
    </aside>
    <div class="container">
      <h3>登録されている音声(<%= current_user.gogakus.count %>)</h3>
      <%= render 'shared/feed' %>
      
    </div>

  </div>

<% else %>
  <div class="center jumbotron">
    
    <h2>自分で音声を設定できるディクテーションアプリ</h2>

    <h1 class="signboard">DICTUM</h1>

    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      
    <%= link_to "Please try a sample!", demo_path, class: "btn btn-lg btn-info",data: { 'turbolinks': false } %>
  </div>

<div class="picture">
  <figure class="picture1"><img src="/assets/Translator-bro.svg" alt="image"></figure>
  <p class="side_text">自分で音声を設定できるので、<br>好きな言語で勉強できます</p>
</div>
<div class="picture">
  <p class="side_text">「Please try a sample!」をクリックすると、<br>サンプルを体験できます</p>
  <figure class="picture2"><img src="/assets/Internet Day-bro.svg" alt="image"></figure>
  
</div>
<% end %>

app/views/static_pages/quick.html.erb
<script src="https://unpkg.com/wavesurfer.js@6.0.4/dist/wavesurfer.js" type="text/javascript"></script>
<%# <script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js"></script> %>
<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js" type="text/javascript"></script>

<h1><u>操作方法</u></h1>
<div class="how-to-play">
    <h4>基本は画面クリックで操作をします。なお、「区域ループ再生」は区域の右側をクリックすることでループから脱出できます。</h4>
    <h4>・ctrl(コントロールキー) = スタート/ストップ ()<br>・←(左カーソルキー) = 3秒戻る <br>・→(右カーソルキー) = 3秒進む  </h4>
</div>
<%# <h5>(注意)保存された音声ファイルが大きかったり、ブラウザの戻るボタンを押した場合にエラーが発生する場合がございます。<br>
可能な限り、ブラウザの戻るボタンではなく、ページ左下の「マイページへ戻る」をご使用ください。
万が一エラーが発生した場合は、お手数ですがページのリロードをお願い致します。
</h5> %>
 <input id="audio_file" type="file" accept="audio/*" />

    <div id="waveform"> </div>

    <div style="text-align: center">
        
        <p class="row">
            <div class="col-xs-1">
                <i class="glyphicon glyphicon-zoom-in"></i>
            </div>

            <div class="col-xs-10">
                <input id="slider" type="range" min="1" max="200" value="1" style="width: 100%" />
            </div>

            <div class="col-xs-1">
                <i class="glyphicon glyphicon-zoom-out"></i>
            </div>
        </p>
    </div>

<div class="container" style="text-align: center">
    <div class="controls" >
        <span>
            <button class="btn btn-primary col-sm-2" onclick="wavesurfer.skipBackward(5)"><i class="fa fa-step-backward"></i>5秒戻る</button>
            <button class="btn btn-primary col-sm-2" onclick="wavesurfer.playPause()"><i class="fa fa-play"></i>スタート/<i class="fa fa-pause"></i>ストップ</button>
            <button class="btn btn-primary col-sm-2" onclick="wavesurfer.skipForward(5)"><i class="fa fa-step-forward"></i>5秒進む</button>
            <select id="controller" class="btn btn-primary col-sm-2">
                <option type="button" value="0.5">0.5</option>
                <option type="button" value="0.75">0.75</option>
                <option type="button" value="1.0" selected>1.0</option>
                <option type="button" value="1.25">1.25</option>
                <option type="button" value="1.5">1.5</option>     
                <option type="button" value="1.75">1.75</option>
                <option type="button" value="2.0">2.0</option>
            </select>
            <button class="btn btn-primary col-sm-2" id="loop">区域ループ再生</button>
           
        </span>
    </div>
</div>

<script>
    var wavesurfer = WaveSurfer.create({
            barRadius: 3,
            cursorWidth: 1,
            height: 230,barMinHeight: 1,
            barGap: 1,
            container: '#waveform',
            waveColor: 'gray',
            progressColor: 'orange',
            scrollParent: true,
            backend: 'MediaElementWebAudio',
            plugins: [
                WaveSurfer.regions.create({
               
                    regions: [
                        {
                            start: 5,
                            end: 7,
                            loop: false,
                            color: 'hsla(200, 50%, 70%, 0.4)',
                        }
                    ],
           
                })
            ]
    });

audio_file.onchange = function () {
    let files = this.files;
    let file = URL.createObjectURL(files[0]);

    var slider = document.querySelector('#slider');

    slider.oninput = function () {
        var zoomLevel = Number(slider.value);
        wavesurfer.zoom(zoomLevel);
    };
    // wavesurfer.load(file);

    const corsAudio = new Audio(file);
    corsAudio.crossOrigin = true;
    
    wavesurfer.load(corsAudio);

};

wavesurfer.on('ready', () => {
        console.log('ready');
        });
    
        wavesurfer.on('error', () => {
        console.log(Callback);
        });

        function playPause() {
        wavesurfer.playPause();
    }
    
let speed = document.getElementById('controller');

    speed.addEventListener('change', function() {
        let idx = speed.selectedIndex;
        let specon = speed.options[idx].text; 
        console.log(specon);  
        function playbackRate() {
            switch (specon) {
                case 0.5:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 0.75:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                    console.log(specon);  
                    break;
                case 1.25:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 1.5:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 1.75:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 2.0:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                default:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
            }
    }
    playbackRate();
    })
           
document.addEventListener('keydown', keydown_ivent);

    function keydown_ivent(e) {
	
	let key = '';
	switch (e.key) {
        case 'Control':
			wavesurfer.playPause();
			break;
		case 'ArrowLeft':
			wavesurfer.skipBackward(3);
			break;
		case 'ArrowRight':
            wavesurfer.skipForward(3);
			break;
	}
	return false;
}

    let l = document.getElementById('loop');
    l.addEventListener('click', function() {
        let region = Object.values(wavesurfer.regions.list)[0];
        region.playLoop();
    });

</script>

<textarea rows="10" cols="50" placeholder="ここに文字を入力出来ます" class="box"></textarea>
<%= link_to "マイページへ戻る", root_url, class:"btn btn-link" %>

<script>
    function rel() {

        if (window.name != "any") {
            // alert("リロードしました");
            location.reload();
            window.name = "any";
        } else {
            window.name = "";
        }

        }
    // rel();
</script>