config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get     '/help',    to: 'static_pages#help'
  get     '/about',   to: 'static_pages#about'
  get     '/contact', to: 'static_pages#contact'
  get     '/signup',  to: 'dictum_users#new'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy'

  resources :gogakus , except: :index
  get     "/quick",   to:"static_pages#quick"
  get     "demo",     to:"static_pages#demo"
  resources :dictum_users , except: [:index, :show]
end

app/models/gogaku.rb
class Gogaku < ApplicationRecord
    belongs_to :dictum_user
    default_scope -> { order(created_at: :desc) }
    validates :subject,presence:true
    validates :body,   presence:true
    has_one_attached :file
    validates :dictum_user_id, presence: true
    validates :file,presence:true
    validates :file,size:         { less_than: 5.megabytes,
                                      message: "should be less than 5MB" }
end

app/controllers/gogakus_controller.rb
class GogakusController < ApplicationController
    # before_action :set_gogaku, only:[:show,:edit,:update,:destroy]
    before_action :logged_in_user
    # , only: [:index,:show,:new,:create, :destroy]
    before_action :correct_user_g,   only: [:show, :edit, :update, :destroy]
    # def index
    #     @gogakus = Gogaku.all
    # end

    def show
        
        # @gogaku = Gogaku.find(params[:id])
       render :layout => 'g_show'
        # byebug
        
    end 
    
# debugger
        # gon.file = @gogaku.file
    def new
        @gogaku = Gogaku.new
    end

    def create
        @gogaku = current_user.gogakus.build(gogaku_params)
        # @gogaku.file = params[:gogaku][:file]
        # byebug
        if @gogaku.save
            flash[:success] = "登録完了!"
            redirect_to root_url
        else
            @feed_items = current_user.feed.paginate(page: params[:page])
            flash[:danger] = @gogaku.errors.full_messages if @gogaku.errors.any?
            redirect_to new_gogaku_path
        end
        # gogaku_params = params.require(:gogaku).permit(:subject,:body,:num)
        # @gogaku = Gogaku.new(gogaku_params)
        # if @gogaku.save
        #     flash[:notice] = "教科書登録成功"
        #     redirect_to gogakus_path
        # else
        #     flash.now[:alert] = "登録失敗"
        #     render :new
        # end
    end

    def edit
        # @gogaku = Gogaku.find(params[:id])
    end

    def update
        # @gogaku = Gogaku.find(params[:id])

        gogaku_params = params.require(:gogaku).permit(:subject, :body, :file, :answer)
        if @gogaku.update(gogaku_params)
            flash[:notice]="更新成功"
            # @feed_items = current_user.feed.paginate(page: params[:page])
            redirect_to root_url
        else
            flash[:danger] = @gogaku.errors.full_messages if @gogaku.errors.any?
            
            redirect_to controller: :gogakus,action: :edit, id: @gogaku.id
        end
    end

    def destroy
        # @gogaku = Gogaku.find(params[:id])
        @gogaku.destroy
        flash[:notice]="削除しました"
        redirect_to request.referrer || root_url
    end

    private

        # def set_gogaku
        #     @gogaku ||= Gogaku.find(params[:id])
        # end



        def gogaku_params
            params.require(:gogaku).permit(:subject, :body, :file, :answer,)
        end

        def correct_user_g
            @gogaku = current_user.gogakus.find_by(id: params[:id])
            redirect_to root_url if @gogaku.nil?
        end
end

app/views/gogakus/_gogaku.html.erb
<div class="gogakus-frame">
<li id="gogaku-<%= gogaku.id %>">
    <%= link_to gravatar_for(gogaku.dictum_user), root_url %>
<span class="dictum_user"><%= link_to gogaku.dictum_user.name, root_path %></span>
    <span class="subject"><%= gogaku.subject %></span>
    <span class="body"><%= gogaku.body %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(gogaku.created_at) %> ago.
        <% if current_user?(gogaku.dictum_user) %>
           
        <% end %>
    </span>
    
    <div class="text-right">
        <%= link_to "Let's start studying!", gogaku_path(gogaku.id) ,class:"btn btn-lg btn-info glyphicon glyphicon-headphones", data: { 'turbolinks': false }%>
        <%= link_to "edit", edit_gogaku_path(gogaku.id) ,class:"btn btn-lg btn-warning glyphicon glyphicon-pencil" %>
        <%= link_to "delete", gogaku, method: :delete,class:"btn btn-lg btn-danger glyphicon glyphicon-trash",
                                            data: { confirm: "You sure?" } %>
        
    </div>
</li>
</div>

app/views/gogakus/edit.html.erb
<h1>教科書編集</h1>

<% if flash.any? %>
    <% flash.each do |message_type, messages| %>
        <% messages.each do |message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
    <% end %>   
<% end %>

<%= form_with model: @gogaku,  method:"patch" do |f| %>

    <div class = "form-group">
        <label>教科</label>
        <%= f.text_field :subject, class:"form-control"%>
    </div>

    <div class = "form-group">
        <label>内容</label>
        <%= f.text_field :body, class: "form-control" %>
    </div>

    <div class = "form-group">
        <label>音声</label>
        <%= f.file_field :file, class:"form-control" %>
    </div>

    <div class = "form-group">
        <label>答え</label>
        <%= f.text_field :answer, class:"form-control"%>
    </div>

    <%= f.submit "更新" ,class:"btn btn-primary" %>
    <%= link_to "戻る",root_url, class:"btn btn-info" %>
<% end %>

app/views/gogakus/it will be deleted index.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="dictum_user_info">
        <%= render 'shared/dictum_user_info' %>
      </section>
      <section class="gogaku_form">
        <%= link_to "新しい音声を登録", new_gogaku_path, class: "btn btn-success btn-lg"%>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>登録されている音声(<%= current_user.gogakus.count %>)</h3>
      <%= render 'shared/feed' %>
    </div>

  </div>

<% else %>
<div class="center jumbotron">
  <h1>Welcome to the DICTUM</h1>

  <h2>
    This is the home page for the
    <a href="#">DICTUM</a>
    .
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<%# 
<%= link_to image_tag("/assets/matt-ragland-02z1I7gv4ao-unsplash.jpg", alt: "logo", width: "200px"),
                      "#" %> 
<% end %>

app/views/gogakus/new.html.erb
<h1>教材登録</h1>

<% if flash.any? %>
    <% flash.each do |message_type, messages| %>
        <% messages.each do |message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
    <% end %>   
<% end %>
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<%= form_with model: @gogaku do |f| %>
<%# ,name: "GogakuForm",id:"G_id" %>


    <div class = "form-group">
        <label>教科</label>
        <%= f.text_field :subject, class:"form-control",placeholder:"例：英語"%>
    </div>

    <div class = "form-group">
        <label>内容</label>
        <%= f.text_field :body, class:"form-control",placeholder:"例：旅行先での英会話１"%>
    </div>

    <div class = "form-group">
        <label>音声</label>
        <span class="file">
            <%= f.file_field :file,accept:"audio/*",class:"form-control" %>
            <%# <script>
                const maxFileSize=5242880 //アップロードできる最大サイズを指定(1048576=1MB)
                $("input[type=file]").change(function(){ //ファイルがアップロードされたら
                    $(".error_msg").remove() //エラーメッセージ削除
                    let uploaded_file=$(this).prop('files')[0]; //アップロードファイル取得
                    if(maxFileSize < uploaded_file.size){ //もし上限値を超えた場合
                        $(this).val("") //画像を空にする
                        $(this).after("<p class='error_msg'>アップロードできる画像の最大サイズは5MBです</p>") //エラーメッセージ表示
                    }
                })
            </script> ,name:"image[]" %>
        </span>
    </div>
<%# ,id:"audio_file", type:"file" ,accept:"audio/*", name:"title" %>

    <div class = "form-group">
        <label>答え</label>
        <%= f.text_field :answer, class:"form-control",placeholder:"答えは入力しなくても保存可能です"%>
    </div>

<% if current_user.gogakus.count < 5 %>
    <%= f.submit"登録",class:"btn btn-danger"%>
<% else %>
    <h2>これ以上音声を登録出来ません。今ある音声を削除すれば新しく登録出来ます。</h2>
<% end %>

    <%= link_to "戻る", root_url ,class:"btn btn-info"%>
       
<% end %>
<%# <form name="demoForm">
        <div>
            <label for="title-id">タイトル</label>
            <input id="audio_filee" type="file" accept="audio/*" name="title" >
        </div>
    </form> %>
<script type="text/javascript">
  $("#gogaku_file").bind("change", function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
      $("#gogaku_file").val("");
    }
  });
</script>

app/views/gogakus/show.html.erb
<script src="https://unpkg.com/wavesurfer.js@6.0.4/dist/wavesurfer.js" type="text/javascript"></script>

<script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js" type="text/javascript"></script>

<h1><u>操作方法</u></h1>
<div class="how-to-play">
    <h4>基本は画面クリックで操作をします。なお、「区域ループ再生」は区域の右側をクリックすることでループから脱出できます。</h4>
    <h4>・ctrl(コントロールキー) = スタート/ストップ ()<br>・←(左カーソルキー) = 3秒戻る <br>・→(右カーソルキー) = 3秒進む  </h4>
</div>
<h5><span class="red">(注意)</span>保存された音声ファイルが大きかったり、ブラウザの戻るボタンを押した場合にエラーが発生する場合がございます。<br>
可能な限り、ブラウザの戻るボタンではなく、ページ左下の「マイページへ戻る」をご使用ください。<br>
万が一エラーが発生した場合は、お手数ですがページのリロードをお願い致します。<br>
なお、どうしてもエラーが頻繫に発生してしまう場合は、マイページの「クイックモード」をご使用ください。</h5>



<table class = "table table-striped">
    <tr>
        <th>教科</th>
        <td><%= @gogaku.subject%></td>
    </tr>
    <tr>
        <th>中身</th>
        <td><%= @gogaku.body%></td>
    </tr>

    <tr>
        <th>音声</th>
        <td><%= @gogaku.file%></td>
    </tr>

</table>

<%# <input id="audio_file" type="file" accept="audio/*" > %>


<div id="waveform"> </div>


<%# <script type="text/javascript">
  document.write(
    '<script src="draw.js?' + new Date().getTime() + '"><\/script>'
  );
</script> %>


<script type="text/javascript">
    var wavesurfer = WaveSurfer.create({
            barRadius: 3,
            cursorWidth: 1,
            height: 230,barMinHeight: 1,
            barGap: 1,
            container: '#waveform',
            waveColor: 'gray',
            progressColor: 'orange',
            scrollParent: true,
            backend: 'MediaElementWebAudio',
            plugins: [
                WaveSurfer.regions.create({
               
                    regions: [
                        {
                            start: 5,
                            end: 7,
                            loop: false,
                            color: 'hsla(200, 50%, 70%, 0.4)',
                        }
                    ],
           
                })
            ]
    });   
    

  

// audio comes from different domain so need to do this (not related to the bug)
        const corsAudio = new Audio('<%= rails_blob_path(@gogaku.file) %>');
        corsAudio.crossOrigin = true;
    
        wavesurfer.load(corsAudio);
    
        wavesurfer.on('ready', () => {
        console.log('ready');
        });
    
        wavesurfer.on('error', () => {
        console.log(Callback);
        });

        function playPause() {
        wavesurfer.playPause();
    }

</script>


<div class="container" style="text-align: center">
    <div class="controls" >
        <span>
            <button class="btn btn-primary col-sm-2" onclick="wavesurfer.skipBackward(5)"><i class="fa fa-step-backward"></i>5秒戻る</button>
            <button class="btn btn-primary col-sm-2" onclick="wavesurfer.playPause()"><i class="fa fa-play"></i>スタート/<i class="fa fa-pause"></i>ストップ</button>
            <button class="btn btn-primary col-sm-2" onclick="wavesurfer.skipForward(5)"><i class="fa fa-step-forward"></i>5秒進む</button>
            <select id="controller" class="btn btn-primary col-sm-2">
                <option type="button" value="0.5">0.5</option>
                <option type="button" value="0.75">0.75</option>
                <option type="button" value="1.0" selected>1.0</option>
                <option type="button" value="1.25">1.25</option>
                <option type="button" value="1.5">1.5</option>     
                <option type="button" value="1.75">1.75</option>
                <option type="button" value="2.0">2.0</option>
            </select>
            <button class="btn btn-primary col-sm-2" id="loop">区域ループ再生</button>
           
        </span>
    </div>
</div>

<script type="text/javascript">
    
        
    let speed = document.getElementById('controller');

    speed.addEventListener('change', function() {
        let idx = speed.selectedIndex;
        let specon = speed.options[idx].text; 
        console.log(specon);  
        function playbackRate() {
            switch (specon) {
                case 0.5:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 0.75:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                    console.log(specon);  
                    break;
                case 1.25:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 1.5:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 1.75:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                case 2.0:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
                default:
                    rate = specon 
                    wavesurfer.setPlaybackRate(rate);
                     console.log(specon);  
                    break;
            }
    }
    playbackRate();
    })
    
</script>

<script type="text/javascript">
    document.addEventListener('keydown', keydown_ivent);

    function keydown_ivent(e) {
	
	let key = '';
	switch (e.key) {
        case 'Control':
			wavesurfer.playPause();
			break;
		case 'ArrowLeft':
			wavesurfer.skipBackward(3);
			break;
		case 'ArrowRight':
            wavesurfer.skipForward(3);
			break;
	}
	return false;
}

</script>

<script type="text/javascript">
    let l = document.getElementById('loop');
    l.addEventListener('click', function() {
        let region = Object.values(wavesurfer.regions.list)[0];
        region.playLoop();
    });
</script>

        
    <div style="text-align: center" class="isolation">
        <p class="row">
            <div class="col-xs-1">
                <i class="glyphicon glyphicon-zoom-in"></i>
            </div>

            <div class="col-xs-9">
                <input id="slider" type="range" min="1" max="200" value="1" style="width: 100%" />
            </div>

            <div class="col-xs-1">
                <i class="glyphicon glyphicon-zoom-out"></i>
            </div>
        </p>
    </div>    

<script type="text/javascript">
    var slider = document.querySelector('#slider');

    slider.oninput = function () {
        var zoomLevel = Number(slider.value);
        wavesurfer.zoom(zoomLevel);
    };
</script>

<textarea rows="10" cols="50" placeholder="ここに文字を入力出来ます"></textarea>

<div class="hidden_box">
    <label for="label1">クリックして答えを表示</label>
    <input type="checkbox" id="label1"/>
    <div class="hidden_show">
        <table class = "table table-striped">
            <tr>
                <th>答え</th>
                <td><%= @gogaku.answer%></td>
                
            </tr>
        </table>
    </div>
</div>
<%= link_to "マイページへ戻る", root_url, class:"btn btn-link" %>
<%# <%= javascript_pack_tag 'gogakus/show'%> 
<script>
function rel() {

    if (window.name != "any") {
        // alert("リロードしました");
        location.reload();
        window.name = "any";
    } else {
        window.name = "";
    }

    }
// rel();
</script>
<%# <script src="https://unpkg.com/wavesurfer.js/dist/plugin/wavesurfer.regions.min.js"></script> %>